
CREATE TABLE IF NOT EXISTS messages (
    ID_messages INTEGER PRIMARY KEY AUTOINCREMENT, 
    Nombre TEXT NOT NULL,                           
    Email TEXT NOT NULL,
    Mensaje TEXT NOT NULL,
    Fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
